/*QUIERO LA HORAS DEL PROYECTOS CON PERSONAS QEU TRABJAN Y SUS RESPECTIVO UBICACIONES GEOGRAFICAS*/
SELECT HORDETPRO AS "HORA" , PERSONA.NOMPER AS "PERSONA" , 
ubigeo.distubi||' '||ubigeo.provubi||' '||ubigeo.deptubi AS UBIGEO FROM DETALLE_PROYECTO
INNER JOIN PERSONA ON PERSONA.CODPER = DETALLE_PROYECTO.CODPER
INNER JOIN UBIGEO ON UBIGEO.CODUBI = PERSONA.CODUBI;

/*QUIERO UN LISTADO DE NOMBRES DEL PROYECTO CON LAS HORAS DE TRABAJO DE PROYECTOS Y CON RESPONSABILIDAD DE CADA PERSONAL*/

SELECT HORDETPRO AS "HORA" , PERSONA.NOMPER AS "PERSONA" , 
PROYECTO.NOMPRO AS PROYECTO, 
RESPONSABILIDAD.DESCRES AS RESPONSABILIDAD
FROM DETALLE_PROYECTO
INNER JOIN PERSONA ON PERSONA.CODPER = DETALLE_PROYECTO.CODPER
INNER JOIN PROYECTO ON PROYECTO.CODPRO = DETALLE_PROYECTO.CODPRO
INNER JOIN RESPONSABILIDAD ON RESPONSABILIDAD.CODRES = DETALLE_PROYECTO.CODRES;

/*QUIERP LA FECHA DE INICIO DEL DEPARTAMENTO CON CARGOS DEL PERSONAL*/
SELECT detalle_departamento.fecindetdep AS "FECHA DE INICIO",
cargo.nomcar AS CARGOS
FROM DETALLE_DEPARTAMENTO
INNER JOIN CARGO ON CARGO.CODCAR=detalle_departamento.codcar;


/*QUIERO UN LISTADO DE PARIENTES DE LA PERSONA CON SU DISTRITO*/
SELECT PARDETFAM AS "PARIENTES", 
PERSONA.NOMPER AS "NOMBRE DE LA  PERSONA" , 
UBIGEO.DISTUBI AS DISTRITO  FROM DETALLE_FAMILIA
INNER JOIN PERSONA ON PERSONA.CODPER = DETALLE_FAMILIA.CODPER
INNER JOIN UBIGEO ON UBIGEO.CODUBI = PERSONA.CODUBI;
